version: 2.1

executors:
  glotzerlab:
    parameters:
      image:
        type: string
      python-version:
        type: string
    docker:
      - image: glotzerlab/ci:2019.06-<< parameters.image >>
    environment:
      PYTHONPATH: /home/ci/project/build
      PYTHON: "/usr/bin/python<< parameters.python-version >>"
      PYTEST: "/usr/bin/python<< parameters.python-version >> -m pytest"
    working_directory: /home/ci/project

commands:
  checkout_with_submodules:
    steps:
      - checkout:
          path: code
      - run:
          name: Update submodules
          working_directory: code
          command: git submodule update --init

  build:
    parameters:
      cc:
        type: string
      cxx:
        type: string
      cmake:
        type: string
    steps:
      - run:
          name: Configure
          command: |
            export CC=<< parameters.cc >> CXX=<< parameters.cxx >>
            mkdir build
            cd build
            << parameters.cmake >> ../code -DPYTHON_EXECUTABLE=${PYTHON} -DENABLE_EMBREE=ON -DENABLE_OPTIX=OFF -Dembree_DIR=/opt/embree-${EMBREE3_VERSION}.x86_64.linux -GNinja
      - run:
          name: Compile
          command: |
            cd build
            ninja -j3

  test:
    steps:
      - run:
          name: Unit test
          no_output_timeout: 1h
          command: |
            mkdir test-results
            cd code/test
            ${PYTEST} --junit-xml=/home/ci/project/test-results/test.xml
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results

  sphinx:
    steps:
      - run: cd code/doc && sphinx-build -b html -d _build/doctrees -W -n . _build/html
      - run: cd code/doc && sphinx-build -b latex -d _build/doctrees -W -n . _build/latex

jobs:
  build_and_test:
    parameters:
      image:
        type: string
      cc:
        type: string
      cxx:
        type: string
      python-version:
        type: string
      build-docs:
        default: false
        type: boolean
      cmake:
        default: /usr/bin/cmake
        type: string
    executor:
      name: glotzerlab
      image: << parameters.image >>
      python-version: << parameters.python-version >>
    steps:
      - checkout_with_submodules
      - build:
          cc: << parameters.cc >>
          cxx: << parameters.cxx >>
          cmake: << parameters.cmake >>
      - test

  sphinx-docs:
    executor:
      name: glotzerlab
      image: ubuntu18.04
      python-version: "3.6"
    steps:
      - checkout_with_submodules
      - sphinx

workflows:
  workflow:
    jobs:
      - sphinx-docs

      - build_and_test:
          name: clang8-py37
          image: ubuntu19.04
          cc: clang-8
          cxx: clang++-8
          python-version: "3.7"

      - build_and_test:
          name: clang7-py37
          image: ubuntu19.04
          cc: clang-7
          cxx: clang++-7
          python-version: "3.7"

      - build_and_test:
          name: gcc9-py37
          image: ubuntu19.04
          cc: gcc-9
          cxx: g++-9
          python-version: "3.7"

      - build_and_test:
          name: gcc8-py36
          image: ubuntu18.04
          cc: gcc-8
          cxx: g++-8
          python-version: "3.6"

      - build_and_test:
          name: gcc7-py36-docs
          image: ubuntu18.04
          cc: gcc-7
          cxx: g++-7
          python-version: "3.6"
          build-docs: true

      - build_and_test:
          name: gcc6-py36
          image: ubuntu18.04
          cc: gcc-6
          cxx: g++-6
          python-version: "3.6"

      - build_and_test:
          name: gcc5-py36
          image: ubuntu18.04
          cc: gcc-5
          cxx: g++-5
          python-version: "3.6"

      - build_and_test:
          name: gcc48-py36
          image: ubuntu18.04
          cc: gcc-4.8
          cxx: g++-4.8
          python-version: "3.6"

      - build_and_test:
          name: clang6-py36
          image: ubuntu18.04
          cc: clang-6.0
          cxx: clang++-6.0
          python-version: "3.6"

      - build_and_test:
          name: clang5-py36
          image: ubuntu18.04
          cc: clang-5.0
          cxx: clang++-5.0
          python-version: "3.6"
