version: 2

references:
  test_container_config: &test_container_config
    docker:
      - image: joaander/ci:20170807
        environment:
          PYTHONPATH: /root/project/build
    working_directory: /root/project

  load_code: &load_code
    checkout:
      path: code

  build_and_test: &build_and_test
    steps:
      - *load_code
      - run:
          name: Update submodules
          command: cd code && git submodule update --init
      - run:
          name: Configure
          command: mkdir build && cd build && ${CMAKE} ../code -DPYTHON_EXECUTABLE=/usr/bin/python${PYVER} -DENABLE_EMBREE=ON -DENABLE_TBB=ON -DENABLE_CUDA=OFF -DENABLE_OPTIX=OFF -GNinja
      - run:
          name: Compile
          command: cd build && ninja
      - run:
          name: Unit test
          command: mkdir test-results && cd code/test && py.test-${PYVER} --junit-xml=/root/project/test-results/test.xml
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results

jobs:
  gcc48-python27-cmake28:
    <<: *test_container_config
    environment:
      CC: /usr/bin/gcc-4.8
      CXX: /usr/bin/g++-4.8
      PYVER: 2.7
      CMAKE: /opt/cmake-2.8.12/bin/cmake
    <<: *build_and_test

  gcc49-python35:
    <<: *test_container_config
    environment:
      CC: /usr/bin/gcc-4.9
      CXX: /usr/bin/g++-4.9
      PYVER: 3.5
    <<: *build_and_test

  gcc54-python35:
    <<: *test_container_config
    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
      PYVER: 3.5
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  sphinx-docs:
    <<: *test_container_config
    steps:
      - *load_code
      - run: cd code/doc && sphinx-build -b html -d _build/doctrees -W -n . build/html

  clang38-python35:
    <<: *test_container_config
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
      PYVER: 3.5
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

workflows:
  version: 2
  workflow:
    jobs:
      - gcc48-python27-cmake28
      - gcc49-python35
      - gcc54-python35
      - clang38-python35
      - sphinx-docs

