version: 2

references:
  test_container_config: &test_container_config
    docker:
      - image: joaander/ci:20171130
        environment:
          PYTHONPATH: /home/ci/project/build
    working_directory: /home/ci/project

  test_container_config-arch: &test_container_config-arch
    docker:
      - image: joaander/ci:20171206-arch-2
        environment:
          PYTHONPATH: /home/ci/project/build
    working_directory: /home/ci/project

  conda_container_config: &conda_container_config
    docker:
      - image: joaander/conda-build:20180207
    working_directory: /root/project

  load_code: &load_code
    checkout:
      path: code

  update_submodules: &update_submodules
    run:
      name: Update submodules
      working_directory: code
      command: git submodule update --init

  build_and_test: &build_and_test
    steps:
      - *load_code
      - *update_submodules
      - run:
          name: Configure
          command: |
            mkdir build
            cd build
            echo cmake=${CMAKE}
            echo pyver=${PYVER}
            echo cc=${CC}
            echo cxx=${CXX}
            ${CMAKE} ../code -DPYTHON_EXECUTABLE=/usr/bin/python${PYVER} -DENABLE_EMBREE=ON -DENABLE_TBB=ON -DENABLE_CUDA=OFF -DENABLE_OPTIX=OFF -GNinja
      - run:
          name: Compile
          command: |
            cd build
            ninja -j3
      - run:
          name: Unit test
          no_output_timeout: 1h
          command: mkdir test-results && cd code/test && py.test-${PYVER} --junit-xml=/home/ci/project/test-results/test.xml
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results

jobs:
  gcc48-python27-cmake28:
    <<: *test_container_config
    environment:
      CC: /usr/bin/gcc-4.8
      CXX: /usr/bin/g++-4.8
      PYVER: "2.7"
      CMAKE: /opt/cmake-2.8.12/bin/cmake
    <<: *build_and_test

  gcc49-python35:
    <<: *test_container_config
    environment:
      CC: /usr/bin/gcc-4.9
      CXX: /usr/bin/g++-4.9
      PYVER: "3.5"
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  gcc54-python35:
    <<: *test_container_config
    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
      PYVER: "3.5"
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  sphinx-docs:
    <<: *test_container_config
    steps:
      - *load_code
      - run: cd code/doc && sphinx-build -b html -d _build/doctrees -W -n . build/html

  clang38-python35:
    <<: *test_container_config
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
      PYVER: "3.5"
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  gcc72-py36:
    <<: *test_container_config-arch
    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
      PYVER: "3.6"
      CMAKE: /usr/bin
    <<: *build_and_test

  clang50-py36:
    <<: *test_container_config-arch
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
      PYVER: "3.6"
      CMAKE: /usr/bin
    <<: *build_and_test

  conda_build:
    <<: *conda_container_config
    steps:
      - *load_code
      - *update_submodules
      - run:
          name: Compile
          working_directory: code
          no_output_timeout: 1h
          command: conda build conda-recipe
      - run: mv /opt/conda/conda-bld .
      - persist_to_workspace:
          root: .
          paths:
            - conda-bld/linux-64/fresnel-*.tar.bz2

  conda-upload:
    <<: *conda_container_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload
          command: anaconda -t ${ANACONDA_TOKEN} upload --no-progress --force conda-bld/**/*.tar.bz2

workflows:
  version: 2
  workflow:
    jobs:
      - gcc48-python27-cmake28:
          filters:
            branches:
              ignore: release
      - gcc49-python35:
          filters:
            branches:
              ignore: release
      - gcc54-python35:
          filters:
            branches:
              ignore: release
      - clang38-python35:
          filters:
            branches:
              ignore: release
      - sphinx-docs:
          filters:
            branches:
              ignore: release
      - gcc72-py36:
          filters:
            branches:
              ignore: release
      - clang50-py36:
          filters:
            branches:
              ignore: release
      - conda-build:
          filters:
            branches:
              only:
                - maint
                - master
                - release
      - conda-upload:
          context: org-global
          requires:
            - conda-build
          filters:
            branches:
              only: release
