{% set name = "fresnel" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    path: ../

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - numpy
    - cmake
    - embree >=2.10.0
    - tbb
    - nomkl

  run:
    - libgcc-ng        # [linux]
    - libstdcxx-ng     # [linux]
    - python
    - numpy
    - embree >=2.10.0
    - tbb
    - pillow

about:
  home: http://glotzerlab.engin.umich.edu/{{ name }}
  license: BSD 3-clause

